// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	comModel "gfast/app/common/model"
	"gfast/app/system/dao/internal"
	"gfast/app/system/model"
	"github.com/gogf/gf/container/gmap"
	"github.com/gogf/gf/os/gtime"
)

// toolsGenTableDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type toolsGenTableDao struct {
	*internal.ToolsGenTableDao
}

var (
	// ToolsGenTable is globally public accessible object for table tools_gen_table operations.
	ToolsGenTable toolsGenTableDao
)

func init() {
	ToolsGenTable = toolsGenTableDao{
		internal.NewToolsGenTableDao(),
	}
}

// Fill with you ideas below.

// ToolsGenTableSearchReq 分页请求参数
type ToolsGenTableSearchReq struct {
	TableName    string `p:"tableName"`    //表名称
	TableComment string `p:"tableComment"` //表描述
	comModel.PageReq
}

// ToolsGenTableColumnsRes 表与字段组合数据
type ToolsGenTableColumnsRes struct {
	*model.ToolsGenTable
	Columns []*model.ToolsGenTableColumn `json:"columns"`
}

// ToolsGenTableEditReq 生成信息修改参数
type ToolsGenTableEditReq struct {
	TableId        int64                        `p:"tableId" v:"required#主键ID不能为空"`
	TableName      string                       `p:"tableName"  v:"required#表名称不能为空"`
	TableComment   string                       `p:"tableComment"  v:"required#表描述不能为空"`
	ClassName      string                       `p:"className" v:"required#实体类名称不能为空"`
	FunctionAuthor string                       `p:"functionAuthor"  v:"required#作者不能为空"`
	TplCategory    string                       `p:"tplCategory"`
	PackageName    string                       `p:"packageName" v:"required#生成包路径不能为空"`
	ModuleName     string                       `p:"moduleName" v:"required#生成模块名不能为空"`
	BusinessName   string                       `p:"businessName" v:"required#生成业务名不能为空"`
	FunctionName   string                       `p:"functionName" v:"required#生成功能名不能为空"`
	Remark         string                       `p:"remark"`
	Overwrite      string                       `p:"overwrite" v:"required#是否覆盖原有文件不能为空"`
	SortColumn     string                       `p:"sort_column" v:"required#缺省排序字段不能为空"`
	SortType       string                       `p:"sort_type" v:"required#缺省排序方式不能为空"`
	ShowDetail     string                       `p:"show_detail" v:"required#是否有查看详情功能不能为空"`
	Params         string                       `p:"params"`
	Columns        []*model.ToolsGenTableColumn `p:"columns"`
	TreeCode       string                       `p:"tree_code"`
	TreeParentCode string                       `p:"tree_parent_code"`
	TreeName       string                       `p:"tree_name"`
	UserName       string
}

// ToolsGenTableEx 实体扩展
type ToolsGenTableEx struct {
	TableId        int64                    // 编号
	TableName      string                   // 表名称
	TableComment   string                   // 表描述
	ClassName      string                   // 实体类名称
	TplCategory    string                   // 使用的模板（crud单表操作 tree树表操作）
	PackageName    string                   // 生成包路径
	ModuleName     string                   // 生成模块名
	BusinessName   string                   // 生成业务名
	FunctionName   string                   // 生成功能名
	FunctionAuthor string                   // 生成功能作者
	Options        string                   // 其它生成选项
	CreateBy       string                   // 创建者
	CreateTime     *gtime.Time              // 创建时间
	UpdateBy       string                   // 更新者
	UpdateTime     *gtime.Time              // 更新时间
	Remark         string                   // 备注
	Overwrite      bool                     // 是否覆盖原有文件
	SortColumn     string                   // 缺省排序字段
	SortType       string                   // 缺省排序方式 (asc顺序 desc倒序)
	ShowDetail     bool                     // 是否有查看详情功能
	TreeCode       string                   // 树编码字段
	TreeParentCode string                   // 树父编码字段
	TreeName       string                   // 树名称字段
	IsPkInsertable bool                     // 主键是否应该在新增时填写
	IsPkListable   bool                     // 主键是否出现在列表中
	HasTimeColumn  bool                     // 是否有时间类型
	HasCreatedBy   bool                     // 是否有created_by字段
	HasUpdatedBy   bool                     // 是否有updated_by字段
	HasConversion  bool                     // service中是否有转换函数
	Columns        []*ToolsGenTableColumnEx // 表列信息
	EditColumns    []*ToolsGenTableColumnEx // 新增、编辑界面列信息，主键单独判断不在此列
	ListColumns    []*ToolsGenTableColumnEx // 列表界面列信息
	DetailColumns  []*ToolsGenTableColumnEx // 详情界面列信息
	QueryColumns   []*ToolsGenTableColumnEx // 查询表单列信息
	PkColumn       *ToolsGenTableColumnEx   // 主键列信息
	LinkedTables   []*ToolsGenTableLinked   // 关联表信息
}

// ToolsGenTableLinked 关联表
type ToolsGenTableLinked struct {
	TableName      string                 // 表名称
	TableComment   string                 // 表描述
	ClassName      string                 // 实体类名称
	PackageName    string                 // 生成包路径
	ModuleName     string                 // 生成模块名
	BusinessName   string                 // 生成业务名
	OrmWithMapping string                 // orm with 映射信息
	RefColumns     *gmap.ListMap          // 要被查询的所有数据列信息
	LinkedTables   []*ToolsGenTableLinked // 嵌套关联表信息
}
